// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartPalmPlatform.API.Shared.Infrastructure.Persistence.EFC.Configuration;

#nullable disable

namespace SmartPalmPlatform.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260708034853_AddIotDeviceMacToSensorReading")]
    partial class AddIotDeviceMacToSensorReading
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SmartPalmPlatform.API.AgronomicRecommendation.Domain.Model.Aggregates.Recommendation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("AgronomistId")
                        .HasColumnType("int")
                        .HasColumnName("agronomist_id");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("approved_at");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("PlantationId")
                        .HasColumnType("int")
                        .HasColumnName("plantation_id");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("published_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("p_k_recommendations");

                    b.ToTable("recommendations", (string)null);
                });

            modelBuilder.Entity("SmartPalmPlatform.API.AgronomicRecommendation.Domain.Model.Entities.AgronomicIntervention", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<DateTime>("ExecutionDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("execution_date");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("performed_by");

                    b.Property<int>("RecommendationId")
                        .HasColumnType("int")
                        .HasColumnName("recommendation_id");

                    b.HasKey("Id")
                        .HasName("p_k_agronomic_interventions");

                    b.HasIndex("RecommendationId")
                        .HasDatabaseName("i_x_agronomic_interventions_recommendation_id");

                    b.ToTable("agronomic_interventions", (string)null);
                });

            modelBuilder.Entity("SmartPalmPlatform.API.IotDeviceManagement.Domain.Model.Aggregates.EdgeDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("LastConnectivityCheckAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_connectivity_check_at");

                    b.Property<DateTime>("LastSyncAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_sync_at");

                    b.Property<string>("MacAddress")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("mac_address");

                    b.Property<int>("MonitoringZoneId")
                        .HasColumnType("int")
                        .HasColumnName("monitoring_zone_id");

                    b.HasKey("Id")
                        .HasName("p_k_edge_devices");

                    b.HasIndex("MacAddress")
                        .IsUnique()
                        .HasDatabaseName("i_x_edge_devices_mac_address");

                    b.ToTable("edge_devices", (string)null);
                });

            modelBuilder.Entity("SmartPalmPlatform.API.IotDeviceManagement.Domain.Model.Entities.EdgeRegistry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("EdgeMacAddress")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("edge_mac_address");

                    b.Property<string>("IotDeviceMacAddresses")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("iot_device_mac_addresses");

                    b.HasKey("Id")
                        .HasName("p_k_edge_registries");

                    b.ToTable("edge_registries", (string)null);
                });

            modelBuilder.Entity("SmartPalmPlatform.API.IotDeviceManagement.Domain.Model.Entities.IotDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("EdgeDeviceMacAddress")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("edge_device_mac_address");

                    b.Property<string>("MacAddress")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("mac_address");

                    b.HasKey("Id")
                        .HasName("p_k_iot_devices");

                    b.HasIndex("MacAddress")
                        .IsUnique()
                        .HasDatabaseName("i_x_iot_devices_mac_address");

                    b.ToTable("iot_devices", (string)null);
                });

            modelBuilder.Entity("SmartPalmPlatform.API.SensorDataProcessing.Domain.Model.Aggregates.SensorReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("EdgeDeviceMacAddress")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("edge_device_mac_address");

                    b.Property<string>("IotDeviceMacAddress")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("iot_device_mac_address");

                    b.Property<DateTime>("MeasuredAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("measured_at");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.Property<int>("Unit")
                        .HasColumnType("int")
                        .HasColumnName("unit");

                    b.Property<double>("Value")
                        .HasColumnType("double")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("p_k_sensor_readings");

                    b.HasIndex("IotDeviceMacAddress", "MeasuredAt")
                        .HasDatabaseName("i_x_sensor_readings_iot_device_mac_address_measured_at");

                    b.ToTable("sensor_readings", (string)null);
                });

            modelBuilder.Entity("SmartPalmPlatform.API.SensorDataProcessing.Domain.Model.Entities.AgronomicThreshold", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("EdgeDeviceMacAddress")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("edge_device_mac_address");

                    b.Property<string>("IotDeviceMacAddress")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("iot_device_mac_address");

                    b.Property<double>("Max")
                        .HasColumnType("double")
                        .HasColumnName("max");

                    b.Property<double>("Min")
                        .HasColumnType("double")
                        .HasColumnName("min");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("p_k_agronomic_thresholds");

                    b.ToTable("agronomic_thresholds", (string)null);
                });

            modelBuilder.Entity("SmartPalmPlatform.API.AgronomicRecommendation.Domain.Model.Entities.AgronomicIntervention", b =>
                {
                    b.HasOne("SmartPalmPlatform.API.AgronomicRecommendation.Domain.Model.Aggregates.Recommendation", null)
                        .WithMany()
                        .HasForeignKey("RecommendationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_agronomic_interventions_recommendations_recommendation_id");
                });
#pragma warning restore 612, 618
        }
    }
}
