// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartPalmPlatform.API.Shared.Infrastructure.Persistence.EFC.Configuration;

#nullable disable

namespace SmartPalmPlatform.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260709122656_AddOwnershipToEdgeAndIotDevices")]
    partial class AddOwnershipToEdgeAndIotDevices
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SmartPalmPlatform.API.AgronomicRecommendation.Domain.Model.Aggregates.Recommendation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("AgronomistId")
                        .HasColumnType("int")
                        .HasColumnName("agronomist_id");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("approved_at");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("PlantationId")
                        .HasColumnType("int")
                        .HasColumnName("plantation_id");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("published_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("p_k_recommendations");

                    b.ToTable("recommendations", (string)null);
                });

            modelBuilder.Entity("SmartPalmPlatform.API.AlertsAndNotifications.Domain.Model.Aggregates.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("level");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("message");

                    b.Property<int>("SensorType")
                        .HasColumnType("int")
                        .HasColumnName("sensor_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("timestamp");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_alerts");

                    b.ToTable("alerts", (string)null);
                });

            modelBuilder.Entity("SmartPalmPlatform.API.AlertsAndNotifications.Domain.Model.Entities.UserAlertSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<bool>("IsMuted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_muted");

                    b.Property<int>("SensorType")
                        .HasColumnType("int")
                        .HasColumnName("sensor_type");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_user_alert_settings");

                    b.HasIndex("UserId", "SensorType")
                        .IsUnique()
                        .HasDatabaseName("i_x_user_alert_settings_user_id_sensor_type");

                    b.ToTable("user_alert_settings", (string)null);
                });

            modelBuilder.Entity("SmartPalmPlatform.API.CropMonitoring.Domain.Model.Aggregates.Plantation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<decimal>("Hectares")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("hectares");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<int>("PalmGrowerId")
                        .HasColumnType("int")
                        .HasColumnName("palm_grower_id");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_plantations");

                    b.ToTable("plantations", (string)null);
                });

            modelBuilder.Entity("SmartPalmPlatform.API.CropMonitoring.Domain.Model.Entities.Sector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ActivatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("activated_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("IotDeviceMacAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("iot_device_mac_address");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("PlantationId")
                        .HasColumnType("int")
                        .HasColumnName("plantation_id");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("p_k_sectors");

                    b.HasIndex("IotDeviceMacAddress")
                        .IsUnique()
                        .HasDatabaseName("i_x_sectors_iot_device_mac_address");

                    b.HasIndex("PlantationId")
                        .HasDatabaseName("i_x_sectors_plantation_id");

                    b.ToTable("sectors", (string)null);
                });

            modelBuilder.Entity("SmartPalmPlatform.API.FieldTechnicalManagement.Domain.Model.Entities.AgronomicIntervention", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<DateTime>("ExecutionDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("execution_date");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("performed_by");

                    b.Property<int?>("RecommendationId")
                        .HasColumnType("int")
                        .HasColumnName("recommendation_id");

                    b.Property<int>("SectorId")
                        .HasColumnType("int")
                        .HasColumnName("sector_id");

                    b.HasKey("Id")
                        .HasName("p_k_agronomic_interventions");

                    b.ToTable("agronomic_interventions", (string)null);
                });

            modelBuilder.Entity("SmartPalmPlatform.API.IAM.Domain.Model.Aggregates.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("BillingCycle")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("billing_cycle");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("end_date");

                    b.Property<int?>("MaxHectares")
                        .HasColumnType("int")
                        .HasColumnName("max_hectares");

                    b.Property<int?>("MaxSensors")
                        .HasColumnType("int")
                        .HasColumnName("max_sensors");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("plan_name");

                    b.Property<string>("PlanType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("plan_type");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_subscriptions");

                    b.ToTable("subscriptions");
                });

            modelBuilder.Entity("SmartPalmPlatform.API.IAM.Domain.Model.Aggregates.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("full_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password_hash");

                    b.Property<int>("Role")
                        .HasColumnType("int")
                        .HasColumnName("role");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<int?>("SubscriptionId")
                        .HasColumnType("int")
                        .HasColumnName("subscription_id");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("p_k_users");

                    b.ToTable("users");
                });

            modelBuilder.Entity("SmartPalmPlatform.API.IAM.Domain.Model.Entities.PaymentTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("period_end");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("period_start");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("plan_name");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("processed_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("transaction_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_payment_transactions");

                    b.ToTable("payment_transactions");
                });

            modelBuilder.Entity("SmartPalmPlatform.API.IotDeviceManagement.Domain.Model.Aggregates.EdgeDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("LastConnectivityCheckAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_connectivity_check_at");

                    b.Property<DateTime>("LastSyncAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_sync_at");

                    b.Property<string>("MacAddress")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("mac_address");

                    b.Property<int>("MonitoringZoneId")
                        .HasColumnType("int")
                        .HasColumnName("monitoring_zone_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_edge_devices");

                    b.HasIndex("MacAddress")
                        .IsUnique()
                        .HasDatabaseName("i_x_edge_devices_mac_address");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_edge_devices_user_id");

                    b.ToTable("edge_devices", (string)null);
                });

            modelBuilder.Entity("SmartPalmPlatform.API.IotDeviceManagement.Domain.Model.Entities.EdgeRegistry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("EdgeMacAddress")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("edge_mac_address");

                    b.Property<string>("IotDeviceMacAddresses")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("iot_device_mac_addresses");

                    b.HasKey("Id")
                        .HasName("p_k_edge_registries");

                    b.ToTable("edge_registries", (string)null);
                });

            modelBuilder.Entity("SmartPalmPlatform.API.IotDeviceManagement.Domain.Model.Entities.IotDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("EdgeDeviceMacAddress")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("edge_device_mac_address");

                    b.Property<string>("MacAddress")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("mac_address");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_iot_devices");

                    b.HasIndex("MacAddress")
                        .IsUnique()
                        .HasDatabaseName("i_x_iot_devices_mac_address");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_iot_devices_user_id");

                    b.ToTable("iot_devices", (string)null);
                });

            modelBuilder.Entity("SmartPalmPlatform.API.SensorDataProcessing.Domain.Model.Aggregates.SensorReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("EdgeDeviceMacAddress")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("edge_device_mac_address");

                    b.Property<string>("IotDeviceMacAddress")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("iot_device_mac_address");

                    b.Property<DateTime>("MeasuredAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("measured_at");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.Property<int>("Unit")
                        .HasColumnType("int")
                        .HasColumnName("unit");

                    b.Property<double>("Value")
                        .HasColumnType("double")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("p_k_sensor_readings");

                    b.HasIndex("IotDeviceMacAddress", "MeasuredAt")
                        .HasDatabaseName("i_x_sensor_readings_iot_device_mac_address_measured_at");

                    b.ToTable("sensor_readings", (string)null);
                });

            modelBuilder.Entity("SmartPalmPlatform.API.SensorDataProcessing.Domain.Model.Entities.AgronomicThreshold", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("EdgeDeviceMacAddress")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("edge_device_mac_address");

                    b.Property<string>("IotDeviceMacAddress")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("iot_device_mac_address");

                    b.Property<double>("Max")
                        .HasColumnType("double")
                        .HasColumnName("max");

                    b.Property<double>("Min")
                        .HasColumnType("double")
                        .HasColumnName("min");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("p_k_agronomic_thresholds");

                    b.ToTable("agronomic_thresholds", (string)null);
                });

            modelBuilder.Entity("SmartPalmPlatform.API.CropMonitoring.Domain.Model.Aggregates.Plantation", b =>
                {
                    b.OwnsOne("SmartPalmPlatform.API.CropMonitoring.Domain.Model.ValueObjects.InstallationPlan", "InstallationPlan", b1 =>
                        {
                            b1.Property<int>("PlantationId")
                                .HasColumnType("int");

                            b1.Property<int>("EstimatedSensors")
                                .HasColumnType("int")
                                .HasColumnName("estimated_sensors");

                            b1.Property<string>("Message")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("varchar(500)")
                                .HasColumnName("installation_message");

                            b1.HasKey("PlantationId");

                            b1.ToTable("plantations");

                            b1.WithOwner()
                                .HasForeignKey("PlantationId");
                        });

                    b.OwnsOne("SmartPalmPlatform.API.CropMonitoring.Domain.Model.ValueObjects.PlantationLocation", "Location", b1 =>
                        {
                            b1.Property<int>("PlantationId")
                                .HasColumnType("int");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("varchar(500)")
                                .HasColumnName("address");

                            b1.Property<string>("Coordinates")
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("coordinates");

                            b1.HasKey("PlantationId");

                            b1.ToTable("plantations");

                            b1.WithOwner()
                                .HasForeignKey("PlantationId");
                        });

                    b.Navigation("InstallationPlan")
                        .IsRequired();

                    b.Navigation("Location")
                        .IsRequired();
                });

            modelBuilder.Entity("SmartPalmPlatform.API.CropMonitoring.Domain.Model.Entities.Sector", b =>
                {
                    b.HasOne("SmartPalmPlatform.API.CropMonitoring.Domain.Model.Aggregates.Plantation", null)
                        .WithMany()
                        .HasForeignKey("PlantationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_sectors_plantations_plantation_id");
                });

            modelBuilder.Entity("SmartPalmPlatform.API.IotDeviceManagement.Domain.Model.Aggregates.EdgeDevice", b =>
                {
                    b.HasOne("SmartPalmPlatform.API.IAM.Domain.Model.Aggregates.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_edge_devices_users_user_id");
                });

            modelBuilder.Entity("SmartPalmPlatform.API.IotDeviceManagement.Domain.Model.Entities.IotDevice", b =>
                {
                    b.HasOne("SmartPalmPlatform.API.IAM.Domain.Model.Aggregates.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_iot_devices_users_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
